### ISSUE TITLE
Show account button when connected to unsupported network

### ISSUE THREAD

**Issue by patpedrosa** [GoodDollar/GoodProtocolUI#247] opened 2022-11-02 12:14 UTC
**Bug Description**
When you connect to an unsupported network, the account button disappears.

**Steps to Reproduce**
1. Go to any unsupported network
2. See the account button disappear
...

**Expected Behavior**
Account button should not disappear so that user can switch/disconnect wallets/accounts

**Additional Context**
Bug:
<img width="537" alt="Screen Shot 2022-11-02 at 09 12 05" src="https://user-images.githubusercontent.com/49105975/199487075-f37135a3-0dbc-4d1c-a4c5-438f9df452cc.png">

Desired behavior:
<img width="454" alt="Screen Shot 2022-11-02 at 09 11 54" src="https://user-images.githubusercontent.com/49105975/199487007-7b8c96ba-1447-491a-8424-cd615c998829.png">

**Comment by vldkhh** [comment] 2023-02-20 15:02
@L03TJ3 @johnsmith-gooddollar 
There is no option to disconnect from the chain when the user is connected to the unsupported chain:

![image.png](https://images.zenhubusercontent.com/62ab094a467ea16960bbc0c6/cfb834fa-40c9-408c-8178-924dad78672c)

**Comment by L03TJ3** [comment] 2023-02-20 15:05
Disconnect from account is part of Account Details > (Top-right)
So your screen and bug description are not about the same?

**Comment by L03TJ3** [comment] 2023-02-22 10:23
The issue is not about disconnect, but that the switch network request is not send when using for example wallet-connect

**Comment by L03TJ3** [comment] 2023-02-27 12:04
Likely will be fixed by https://github.com/GoodDollar/GoodWeb3-Mono/pull/53

**Comment by johnsmith-gooddollar** [comment] 2023-03-01 10:16
@L03TJ3 please retest it now at dev

**Comment by L03TJ3** [comment] 2023-03-01 14:55
Bug: switching chain uses hexstring over chainId number

**Comment by johnsmith-gooddollar** [comment] 2023-03-01 18:48
The following error appears if I have **NO CELO** in my MetaMask configured

![image.png](https://images.zenhubusercontent.com/6135d0416eed5f7809f4ee6b/cf1f4618-2269-423b-ad92-9451df40e28b)

It comes **directly** from the wallet.  Hex values are just standard of JSONRPC calls, don't rely on this. Everything is fine at protocolUI side, the error almost does nothing wrong, just need to handle it properly:

a) should be some UI notification that user should add CELO onto his/her wallet

![image.png](https://images.zenhubusercontent.com/6135d0416eed5f7809f4ee6b/ee713c2a-9a6f-4be5-9005-935e1b05f3de)

b) if then chose unsupported chain on metamaks, the switch network popup shows Celo selected while actually it should show nothing selected like in the case when i chose Ethereum mainnet

![image.png](https://images.zenhubusercontent.com/6135d0416eed5f7809f4ee6b/df8da63c-a19b-4ee5-81cc-cdf1cbf2cdec)

**Comment by L03TJ3** [comment] 2023-03-02 13:14
fixed here: https://github.com/GoodDollar/GoodProtocolUI/commit/2108635c743e8505f2dbc4fa2b46ff9bd23cef71

**Comment by L03TJ3** [comment] 2023-03-03 16:55
Did a hot-fix with no review, so this should still be reviewed I think

**Closed** 2023-03-14 17:36 UTC
Labels: bug, CELO_PHASE_2
