### ISSUE TITLE
[Design QA] Buy G$ & Claim screen / Desktop

### ISSUE THREAD

**Issue by SanaJamm** [GoodDollar/GoodProtocolUI#495] opened 2023-11-28 11:41 UTC
Let's keep the right sections and left sections in same same ratio in all screens (every screen that have two parallel sections)  I fixed it both in the claim and the buy G$ screens.
and let's keep a 32px right padding in screens. right now the news feed is sticked to the right side of the screen.

Design:
<img width="423" alt="Screen Shot 2023-11-28 at 13 38 49" src="https://github.com/GoodDollar/GoodProtocolUI/assets/122018139/f6846568-a960-4db7-aa74-e167e2f71cb1">

**Comment by vldkhh** [comment] 2023-12-04 20:13
@L03TJ3 components are overlapping each other on the claim G$ screen 
<img width="1526" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXN1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--63fba5d5a91cf16ab19f9fd15212a76f2256db4e/Snag_44bd91e7.png" alt="Snag_44bd91e7.png" />

@SanaJamm (cannot tag her) @patpedrosa there is a lot of white space on the BuyG$ screen, I think we need a solution for it 
<img width="1528" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXd1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2f2def3b80b767b0ecefff4778135089cad7aaf4/Snag_44bf60cb.png" alt="Snag_44bf60cb.png" />

**Comment by vldkhh** [comment] 2023-12-06 18:49
@L03TJ3 @SanaJamm need to centralize the post-claim screen. Also the news feed looks smaller as before
<img width="1531" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG83QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7044beb8d95475f47a5bd813e40f71a7e57cb10a/Snag_4ebe374b.png" alt="Snag_4ebe374b.png" />

And this is how the claim screen looks like on Pat's device 
<img width="1242" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHM3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aca6e2da2eecbb6f1cbabf35efd909d1f7bf21db/Snag_4ebf5128.png" alt="Snag_4ebf5128.png" />

**Comment by L03TJ3** [comment] 2023-12-07 04:52
@vldkhh newsfeed is the new size as requested. right container is fixed at 375px (both buy/claim)
left container should fill up the rest of the page

@patpedrosa can you provide screen-size/resolution? or device/type? then I can verify on browserstack whats happening

**Comment by L03TJ3** [comment] 2023-12-07 06:39
@patpedrosa nvm, I think I replicated in brave browser.
should be fixed now, can you verify this on dev.gooddapp.org ? (its being deployed now, should be up in 15 minutes or so)

**Comment by L03TJ3** [comment] 2023-12-07 12:14
Verified all is working, confirmed by both @patpedrosa @vldkhh @SanaJamm

**Comment by vldkhh** [comment] 2023-12-07 18:36
verified on prod

**Closed by vldkhh** 2023-12-07 18:36 UTC
Labels: bug
