### ISSUE TITLE
MicroBridge - recent transfer doesn't look very good on mobile size 

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodProtocolUI#566] opened 2024-07-25 21:25 UTC
**Bug Description**
"Recent Transfers" text wraps in a messy way in the MicroBridge in GoodDapp on mobile

**Steps to Reproduce**
1. Go to GoodDapp on Mobile
2. Begin a microbridge transaction
 
<img width="452" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzhPQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--09441e11bea9689ea3f4bb778122f920f649983e/image.png" alt="image.png" />

**Expected Behavior**
All text is left-justified with the spinner to the left.

**Comment by L03TJ3** [comment] 2024-09-06 10:33
duplicate of this: https://app.zenhub.com/workspaces/goodlabs-61559a6a33275e00141f8ee4/issues/gh/gooddollar/goodweb3-mono/165 

So closing

**Closed by L03TJ3** 2024-09-06 10:33 UTC
Labels: bug
